### ISSUE TITLE
Broken links in SP Schema Registry documentation

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow/iglu-example-schema-registry#5]
https://github.com/snowplow/iglu-example-schema-registry#2-uploading-the-schemas-to-iglu

The two links in section 2 of the documentation lead to 404s:

Upload the schemas to snowplow-mini (for testing) - https://github.com/snowplow/iglu-example-schema-registry/blob/master/snowplow-mini

Upload the schemas to Iglu for the full pipeline - https://github.com/snowplow/iglu-example-schema-registry/blob/master/full

Both processes are described in the subsequent sections of the documentation, so I suspect the linked pages are redundant anyway.

**Comment by adatzer** [comment]
This was fixed in 862f6773 . Closing.
